// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLJ3niwdpRom0qX7lm6oOW7jDifX4I7sA',
    appId: '1:493764159628:ios:0bace98cd6d44bb81bf3a9',
    messagingSenderId: '493764159628',
    projectId: 'hedeyety-79aa8',
    storageBucket: 'hedeyety-79aa8.firebasestorage.app',
    iosBundleId: 'com.ahmedamin.hedeiaty',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM25Q83Ictk7PAqFWDWxWo9i-MquRtytI',
    appId: '1:493764159628:android:046dbed3da338cea1bf3a9',
    messagingSenderId: '493764159628',
    projectId: 'hedeyety-79aa8',
    storageBucket: 'hedeyety-79aa8.firebasestorage.app',
  );

}